attributes:
  user: ["担当者コード", "担当者名称", "admin", "email", "supervisor"]
  bashokubunmst: ["場所区分コード","場所区分名"]
  bashomasters: ["所コード", "場所名", "場所名カナ", "SUB", "場所区分", "会社コード"]
  bunrui: ["分類コード", "分類名"]
  dengonkaitou: ["id", "種類名", "備考"]
  dengonyouken: ["id", "種類名", "備考"]
  eki: ["駅コード", "駅名", "駅名カナ", "選択回数"]
  joutaimaster: ["状態コード", "状態名", "状態区分", "勤怠状態名", "マーク", "色", "文字色", "WEB使用区分", "勤怠使用区分"]
  jobmaster: ["job番号", "job名", "開始日", "終了日", "ユーザ番号", "ユーザ名", "入力社員番号", "分類コード", "分類名", "関連Job番号", "備考"]
  jpt_holiday_msts: ["id", "event_date", "title", "description"]
  kairanyokenmst: ["id", "名称", "備考"]
  kaishamaster: ["会社コード", "会社名", "備考"]
  kikanmst: ["機関コード", "機関名", "備考"]
  kouteimaster: ["所属コード", "工程コード", "工程名"]
  shainmaster: ["社員番号", "連携用社員番号", "氏名", "所属コード", "直間区分", "役職コード", "内線電話番号", "伝言件数", "回覧件数", "所在コード", "有給残数", "残業区分", "勤務タイプ"]
  shoninshamst: ["id", "申請者", "承認者"]
  shozai: ["所在コード", "所在名", "背景色", "文字色"]
  shozokumaster: ["所属コード", "所属名"]
  tsushinseigyou: ["id", "社員番号", "メール", "送信許可区分"]
  yakushokumaster: ["役職コード", "役職名"]
